'use client';

import { useState } from 'react';

interface ModuleDoc {
  id: string;
  icon: string;
  title: string;
  section: string;
  desc: string;
  features: string[];
  steps: string[];
  tips?: string[];
  related?: string[];
}

const modules: ModuleDoc[] = [
  {
    id: 'employee-portal',
    icon: 'user-circle',
    title: 'Employee Self-Service Portal',
    section: 'Self-Service',
    desc: 'The employee portal allows staff to view their dashboard, manage their profile, and access payslips without needing admin assistance.',
    features: [
      'Personal dashboard with leave balance, recent claims, and payslip summary',
      'Profile management including password change',
      'Payslip viewing with detailed printable modal',
    ],
    steps: [
      'Log in with your username and password at /login',
      'You will be redirected to your employee dashboard',
      'View your leave balance, recent claims, and upcoming overtime on the dashboard',
      'Click "My Profile" to update your name, email, or change your password',
      'Click "Payslips" to view and print your payslips',
    ],
    tips: [
      'Default passwords are set by HR — change yours in My Profile on first login',
      'Payslip modal includes a Print button for physical records',
    ],
    related: ['profile', 'payslips'],
  },
  {
    id: 'dashboard',
    icon: 'layout-dashboard',
    title: 'Dashboard',
    section: 'Core',
    desc: 'The main dashboard provides a high-level overview of the entire organisation with live KPIs, charts, and AI-powered executive summary.',
    features: [
      '10 live data sections covering all HR metrics',
      'KPI metric row — total employees, active claims, pending leave, OT hours, attendance',
      'Recent claims and pending leave queues',
      'Department breakdown bar chart',
      'Overtime by day type chart',
      'Payroll snapshot with 6-month trend chart',
      'Employee status distribution with visual bar',
      'Mileage, training, and announcements cards',
      'AI executive summary generated by DeepSeek',
    ],
    steps: [
      'Navigate to Dashboard from the sidebar',
      'All metrics load automatically from live data',
      'Hover over charts for detailed values',
      'Scroll down to see the AI executive summary at the bottom',
      'Click on any metric card to explore that module',
    ],
    tips: [
      'The dashboard refreshes on each page load',
      'The AI summary provides actionable insights based on current data',
    ],
    related: ['reports', 'ask-ai'],
  },
  {
    id: 'employees',
    icon: 'users',
    title: 'Employees',
    section: 'Core',
    desc: 'Manage all employee records — add, edit, view, and terminate employees. This is the central employee registry.',
    features: [
      'Employee list with search, department filter, and status badges',
      'Add new employee with full details (employee ID, name, role, dept, type, status)',
      'Edit existing employee records',
      'Delete employees with confirmation',
      'AI insight panel for workforce analysis',
    ],
    steps: [
      'Go to Employees from the sidebar',
      'Use the search bar to find employees by name or ID',
      'Click the department pills to filter by department',
      'Click "Add Employee" to create a new record',
      'Fill in the required fields and submit',
      'Click the edit icon on any row to modify details',
      'Click the delete icon to remove a record (with confirmation)',
    ],
    tips: [
      'Employee IDs must be unique (e.g., E138, E139)',
      'Changing an employee status to "Inactive" will prevent portal access',
    ],
    related: ['directory', 'history'],
  },
  {
    id: 'payroll',
    icon: 'cash',
    title: 'Payroll & EPF/SOCSO',
    section: 'Core',
    desc: 'Manage payroll records including gross salary, statutory deductions (EPF, SOCSO, EIS), and net pay calculations.',
    features: [
      'Payroll records with month/year filtering',
      'Gross pay, EPF, SOCSO, EIS, and net pay columns',
      'Approved/pending status badges',
      'AI-powered payroll insights',
    ],
    steps: [
      'Go to Payroll from the sidebar',
      'Select month and year to view records for a specific period',
      'View each employee\'s gross pay and deductions',
      'Green badge = Approved, amber badge = Pending',
      'AI insight panel at the top analyses payroll trends',
    ],
    tips: [
      'EPF employee contribution is 11% of gross salary',
      'SOCSO is 0.5% employee + 1.75% employer',
      'EIS is 0.2% employee + 0.2% employer',
    ],
    related: ['e-submissions', 'reports'],
  },
  {
    id: 'e-submissions',
    icon: 'file-export',
    title: 'E-Submissions & Bank File Generation',
    section: 'Core',
    desc: 'Generate statutory submission files for EPF/KWSP, SOCSO/PERKESO, EIS/SIP, PCB/CP39, Borang E, and bank file IBG for salary crediting.',
    features: [
      '6 report types — Bank File IBG, EPF KWSP, SOCSO, EIS, PCB CP39, Borang E',
      'Month and year selector for reporting period',
      'CSV file download for each report type',
      'Generation history table with timestamps',
    ],
    steps: [
      'Go to E-Submissions from the sidebar',
      'Select the month and year for the report',
      'Click the report type card you need (e.g., EPF/KWSP)',
      'The CSV file will download automatically',
      'Upload the generated file to the respective statutory portal',
    ],
    tips: [
      'Bank File IBG format is compatible with major Malaysian banks',
      'Borang E is the annual tax return format',
    ],
    related: ['payroll', 'reports'],
  },
  {
    id: 'leave',
    icon: 'calendar-off',
    title: 'Leave Management',
    section: 'Workforce',
    desc: 'Track and manage employee leave requests including annual leave, medical leave, emergency leave, and unpaid leave.',
    features: [
      'Leave request list with type, date range, reason, and status',
      'Leave balance display for each employee',
      'Status badges — Approved (green), Pending (amber), Rejected (red)',
      'AI-powered leave analysis and insights',
      'Compliant with EA 1955 Section 60F',
    ],
    steps: [
      'Go to Leave from the sidebar',
      'View all leave requests with employee names and details',
      'Green = Approved, Amber = Pending, Red = Rejected',
      'Leave balances are shown at the top',
      'AI insight panel provides leave trend analysis',
    ],
    tips: [
      'Permanent staff: 14 days annual leave per year',
      'Medical leave: 14 days outpatient, 60 days hospitalisation',
      'Submit at least 7 days in advance for planned leave',
    ],
    related: ['calendar', 'employee-portal'],
  },
  {
    id: 'overtime',
    icon: 'clock-bolt',
    title: 'Overtime (OT)',
    section: 'Workforce',
    desc: 'Log and manage overtime hours with automatic rate calculation based on day type (normal, weekend, public holiday).',
    features: [
      'OT log with employee, date, hours, day type, and amount',
      'Multiplier rates — 1.5x normal, 2.0x weekend, 3.0x public holiday',
      'Status tracking — Approved, Pending',
      'AI OT analysis and insights',
    ],
    steps: [
      'Go to Overtime from the sidebar',
      'View all OT records with calculated amounts',
      'The rate is automatically calculated based on day type',
      'Approved items have green badge, pending have amber',
      'Use the AI insight panel for OT trend analysis',
    ],
    tips: [
      'Hourly rate = Monthly salary / 26 days / 8 hours',
      'OT beyond 8 hours on a rest day is 3.0x',
      'Public holiday OT is 3.0x for first 8 hours, 4.0x beyond',
    ],
    related: ['payroll', 'attendance'],
  },
  {
    id: 'attendance',
    icon: 'fingerprint',
    title: 'Attendance',
    section: 'Workforce',
    desc: 'Record and monitor daily employee attendance with clock-in/out times and status tracking.',
    features: [
      'Attendance log with date, clock-in, clock-out',
      'Status — Present, Late, Absent',
      'Per-employee attendance view',
      'AI attendance pattern insights',
    ],
    steps: [
      'Go to Attendance from the sidebar',
      'View daily attendance records for all employees',
      'Present = green, Late = amber, Absent = red',
      'Use the AI insight panel to identify attendance patterns',
    ],
    tips: [
      'Employees clocking in after 9:00 AM are marked as Late',
      'Attendance feeds into payroll for leave deduction',
    ],
    related: ['overtime', 'payroll'],
  },
  {
    id: 'claims',
    icon: 'receipt',
    title: 'Claims',
    section: 'Field Services',
    desc: 'Manage employee expense claims including mileage, lodging, and meals with approval workflow.',
    features: [
      'Claims list with type, date, locations, distance, and amount',
      'Status tracking — Pending, Approved, Rejected',
      'Per-claim breakdown with details',
      'AI claims analysis and insights',
    ],
    steps: [
      'Go to Claims from the sidebar',
      'View all claims with employee details',
      'Pending claims have amber badge, Approved = green, Rejected = red',
      'Click on a claim to view full details',
      'Use AI insights for spending pattern analysis',
    ],
    tips: [
      'Mileage rate: RM 0.60 per km',
      'Lodging requires official receipt',
      'Claims must be submitted within 30 days',
    ],
    related: ['mileage', 'approvals'],
  },
  {
    id: 'mileage',
    icon: 'car',
    title: 'Mileage Tracker',
    section: 'Field Services',
    desc: 'Track employee mileage for business travel with distance-based reimbursement calculations.',
    features: [
      'Mileage records with from/to locations and distance',
      'Automatic amount calculation at RM 0.60/km',
      'Status tracking — Pending, Approved, Rejected',
      'AI mileage insights',
    ],
    steps: [
      'Go to Mileage from the sidebar',
      'View all mileage claims with distances and amounts',
      'Pending = amber, Approved = green, Rejected = red',
      'Use the AI panel for mileage trend analysis',
    ],
    tips: [
      'Rate is RM 0.60 per kilometre (standard Malaysia rate)',
      'GPS odometer readings are recommended for verification',
    ],
    related: ['claims', 'reports'],
  },
  {
    id: 'recruitment',
    icon: 'users-plus',
    title: 'Recruitment / ATS',
    section: 'Recruitment',
    desc: 'Full Applicant Tracking System with job postings, kanban pipeline, and interview scheduling.',
    features: [
      '4 metric cards — Active Jobs, Total Applicants, Interviews This Week, Hired This Month',
      'Jobs tab — table with job title, department, type, status',
      'Kanban Pipeline tab — 7-stage board: Applied, Screened, Shortlisted, Interviewed, Offered, Accepted, Rejected',
      'Interviews tab — scheduled interview list',
      'Per-job pipeline detail page',
      'Schedule interview modal from pipeline',
    ],
    steps: [
      'Go to Recruitment from the sidebar',
      'View the 4 metric cards for quick stats',
      'Click "Jobs" tab to see all job postings — click a job to see its pipeline',
      'Click "Pipeline" tab to see the kanban board with all applicants',
      'Drag and drop (or click to move) applicants between stages',
      'Click "Interviews" tab to see all scheduled interviews',
      'From a job\'s pipeline page, click "Schedule Interview" to set one up',
    ],
    tips: [
      'Pipeline stages map to: Applied → Screened → Shortlisted → Interviewed → Offered → Accepted → Rejected',
      'Interview slots can be assigned to specific interviewers',
    ],
    related: ['directory', 'calendar'],
  },
  {
    id: 'training',
    icon: 'book',
    title: 'Training & Development',
    section: 'HR Tools',
    desc: 'Manage employee training programmes including providers, types, costs, and certifications.',
    features: [
      '4 metric cards — Total, Completed, In Progress, Planned',
      'Training records table with provider, type, date, cost',
      'Certification tracking with status badges',
      'AI training analysis and insights',
    ],
    steps: [
      'Go to Training from the sidebar',
      'View the metrics cards at the top for a quick summary',
      'Scroll to see the training records table',
      'Click "Add Training" to create a new record',
      'Fill in training title, provider, type, dates, cost, and certification',
      'Use AI insights for training effectiveness analysis',
    ],
    tips: [
      'HRDF levy can be used for approved training programmes',
      'Certification expiry dates should be tracked in the system',
    ],
    related: ['employees', 'reports'],
  },
  {
    id: 'assets',
    icon: 'tool',
    title: 'Asset Management',
    section: 'HR Tools',
    desc: 'Track company assets assigned to employees including serial numbers, purchase prices, and assignment status.',
    features: [
      '4 metric cards — Total, Assigned, Available, Total Value',
      'Asset list with serial number, type, purchase price, assignment',
      'Type filter pills for easy filtering',
      'Status colours — Assigned (green), Available (blue), Retired (red)',
    ],
    steps: [
      'Go to Assets from the sidebar',
      'View the metrics cards for asset summary',
      'Use type filter pills to filter by asset category',
      'Click "Add Asset" to register a new asset',
      'Assign assets to employees when issuing equipment',
    ],
    tips: [
      'Assets can be laptops, phones, vehicles, tools, etc.',
      'Retired assets should be marked as Retired for audit trail',
    ],
    related: ['employees', 'reports'],
  },
  {
    id: 'performance',
    icon: 'chart-arrows',
    title: 'Performance Management',
    section: 'HR Tools',
    desc: 'Track employee performance scores by quarter with trend analysis and AI insights.',
    features: [
      'Performance records with score, quarter, and year',
      'Colour-coded scores — high (green), medium (amber), low (red)',
      'AI performance analysis and insights',
    ],
    steps: [
      'Go to Performance from the sidebar',
      'View performance scores for all employees',
      'Green = 80+, Amber = 60-79, Red = below 60',
      'Use the AI panel for performance trend analysis',
    ],
    tips: [
      'Performance reviews are conducted quarterly (Q1-Q4)',
      'Scores below 50 trigger a Performance Improvement Plan',
    ],
    related: ['employees', 'training'],
  },
  {
    id: 'foreign',
    icon: 'world',
    title: 'Foreign Workers',
    section: 'HR Tools',
    desc: 'Manage foreign worker records including permit types, levy payments, FOMEMA status, and security bonds.',
    features: [
      'Foreign worker list with nationality, permit type, and expiry',
      'Levy payment tracking — Paid (green) or Unpaid (red)',
      'FOMEMA status — Due (amber) or Cleared (green)',
      'Security bond amount tracking',
      'AI foreign worker insights',
    ],
    steps: [
      'Go to Foreign Workers from the sidebar',
      'View all foreign worker records with permit details',
      'Monitor permit expiry dates for renewal',
      'Track levy payment and FOMEMA status',
      'Use AI insights for compliance analysis',
    ],
    tips: [
      'Permit types include VP(TE), PLKS, and LTSVP',
      'Levy must be paid annually before permit renewal',
      'FOMEMA medical check-up is mandatory annually',
    ],
    related: ['levy', 'reports'],
  },
  {
    id: 'levy',
    icon: 'calculator',
    title: 'Levy Calculator',
    section: 'HR Tools',
    desc: 'Calculate foreign worker levy amounts based on sector, worker category, and permit type.',
    features: [
      'Levy calculation with sector and category selection',
      'Clear display of calculated levy amount',
      'Reference to current Malaysia levy rates',
    ],
    steps: [
      'Go to Levy Calculator from the sidebar',
      'Enter the sector, worker category, and number of workers',
      'The system calculates the total levy amount',
      'Use this to budget for foreign worker costs',
    ],
    tips: [
      'Levy rates differ by sector (manufacturing, services, construction, etc.)',
      'Levy is paid annually to the Immigration Department',
    ],
    related: ['foreign', 'payroll'],
  },
  {
    id: 'documents',
    icon: 'files',
    title: 'Documents',
    section: 'HR Tools',
    desc: 'Manage employee documents with issue/expiry date tracking and expiry alert banners.',
    features: [
      'Document list with type, issue date, and expiry date',
      'Expiry alert banners — red (expired), amber (expires soon)',
      'Type filter pills for easy sorting',
      'Status badges — Active (green), Expires in Xd (amber), Expired (red)',
    ],
    steps: [
      'Go to Documents from the sidebar',
      'View all documents with their expiry status',
      'Red banner = expired, Amber banner = expiring within 30 days',
      'Use filter pills to sort by document type',
      'Click "Add Document" to upload a new document',
    ],
    tips: [
      'Document types include Passport, Work Permit, MC, Offer Letter, etc.',
      'Set up alerts for documents expiring within 30 days',
    ],
    related: ['employees', 'foreign'],
  },
  {
    id: 'history',
    icon: 'timeline',
    title: 'Employee History',
    section: 'HR Tools',
    desc: 'Track employee job changes including promotions, transfers, salary adjustments, and terminations on a timeline.',
    features: [
      'Timeline cards for each employee\'s job changes',
      'Change type filter pills — Promotion, Transfer, Salary Adjustment, Termination',
      'Old → new value display with strikethrough for changed items',
      'Colour-coded change types',
    ],
    steps: [
      'Go to Employee History from the sidebar',
      'View the timeline of all changes across employees',
      'Use filter pills to see specific change types',
      'Each card shows the old value (strikethrough) → new value',
    ],
    tips: [
      'Promotions are shown in green, Terminations in red',
      'Salary adjustments show the before and after amount',
    ],
    related: ['employees', 'performance'],
  },
  {
    id: 'directory',
    icon: 'address-book',
    title: 'Employee Directory',
    section: 'HR Tools',
    desc: 'A searchable employee directory with department filter and card grid layout.',
    features: [
      'Search bar for finding employees by name',
      'Department filter pills',
      'Card grid with avatar initials, name, role, department, status',
      'Quick visual reference for the whole organisation',
    ],
    steps: [
      'Go to Directory from the sidebar',
      'Use the search bar to find specific employees',
      'Click department pills to filter by department',
      'Cards display initials, full name, role, and department',
    ],
    tips: [
      'Avatar colours are based on the employee\'s department',
      'Inactive employees show a muted status',
    ],
    related: ['employees', 'org-chart'],
  },
  {
    id: 'org-chart',
    icon: 'hierarchy-2',
    title: 'Organisation Chart',
    section: 'HR Tools',
    desc: 'Visual org chart grouping employees by department with manager cards and team members.',
    features: [
      'Department-based grouping',
      'Manager card with team member list',
      'Colour-coded by department',
      'Clear hierarchy visualisation',
    ],
    steps: [
      'Go to Org Chart from the sidebar',
      'View all departments with their managers and team members',
      'Each department has a unique colour',
      'Manager is shown at the top with team below',
    ],
    tips: [
      'Departments follow the organisation\'s reporting structure',
      'Click on an employee to view their profile',
    ],
    related: ['directory', 'employees'],
  },
  {
    id: 'calendar',
    icon: 'calendar-month',
    title: 'HR Calendar',
    section: 'HR Tools',
    desc: 'A month-view calendar that aggregates events from leave, interviews, training, and document expiries.',
    features: [
      'Month grid view with prev/next navigation',
      'Events colour-coded by type — Leave (teal), Interview (purple), Training (amber), Expiry (red)',
      'Day detail panel on click',
      'Data sourced from live APIs',
    ],
    steps: [
      'Go to Calendar from the sidebar',
      'Navigate between months using the prev/next arrows',
      'Click on a day to view events in the detail panel',
      'Events are colour-coded for quick identification',
    ],
    tips: [
      'Leave events appear in teal, interviews in purple',
      'Expiring documents appear in red',
    ],
    related: ['leave', 'recruitment', 'training', 'documents'],
  },
  {
    id: 'announcements',
    icon: 'speakerphone',
    title: 'Announcements',
    section: 'HR Tools',
    desc: 'Create and manage company announcements with priority highlighting and expiry dates.',
    features: [
      'Announcement list with category and priority',
      'Priority highlighting — High (red border), Normal (default)',
      'Expired badge for past announcements',
      'Category filter pills',
    ],
    steps: [
      'Go to Announcements from the sidebar',
      'View all current announcements',
      'High-priority announcements have a red left border',
      'Use category pills to filter by type',
      'Click "Add Announcement" to create a new one',
    ],
    tips: [
      'High-priority announcements appear at the top',
      'Expired announcements are dimmed automatically',
    ],
    related: ['dashboard', 'employee-portal'],
  },
  {
    id: 'reports',
    icon: 'file-analytics',
    title: 'Reports & Analytics',
    section: 'HR Tools',
    desc: 'AI-powered reporting module with 10 report types, DeepSeek AI summaries, CSV export, and print support.',
    features: [
      '10 report types — Payroll Summary, Leave Analysis, Employee Demographics, Claims Summary, Training ROI, Overtime Analysis, Attendance Summary, Assets Summary, Recruitment Funnel, Foreign Worker Summary',
      'Live database queries for each report',
      'DeepSeek AI-generated executive summary',
      'CSV export for all reports',
      'Print-friendly layout',
    ],
    steps: [
      'Go to Reports from the sidebar',
      'Select a report type from the cards',
      'Choose the relevant period or filters',
      'Click "Generate" to create the report',
      'View the AI summary at the top',
      'Click "CSV" to download or "Print" for a physical copy',
    ],
    tips: [
      'AI summaries provide actionable insights for each report',
      'CSV files can be opened in Excel or Google Sheets',
    ],
    related: ['payroll', 'leave', 'employees', 'dashboard'],
  },
  {
    id: 'approvals',
    icon: 'git-branch',
    title: 'Approval Workflow',
    section: 'Approvals',
    desc: 'Centralised approval queue for pending claims, leave requests, and other approvals requiring manager action.',
    features: [
      'Approval queue with type, reference, level, and status',
      'Pending items clearly marked for action',
      'Approved/rejected tracking',
      'Multi-level approval support',
    ],
    steps: [
      'Go to Approval Workflow from the sidebar',
      'View all pending approvals requiring your action',
      'Pending items show with amber badge',
      'Click to approve or reject with comments',
    ],
    tips: [
      'Approval levels match the organisation hierarchy',
      'Level 1 = direct manager, Level 2 = department head',
    ],
    related: ['claims', 'leave', 'matrix'],
  },
  {
    id: 'matrix',
    icon: 'table',
    title: 'Approval Matrix',
    section: 'Approvals',
    desc: 'View and configure the approval hierarchy matrix defining approval limits and routing rules.',
    features: [
      'Approval matrix table with hierarchy levels',
      'Clear overview of approval limits',
      'Configure who approves what',
    ],
    steps: [
      'Go to Approval Matrix from the sidebar',
      'View the approval hierarchy for each department',
      'Each level shows the maximum approval amount',
    ],
    tips: [
      'Matrix follows the organisation hierarchy level',
      'Higher levels can override lower levels',
    ],
    related: ['approvals', 'admin'],
  },
  {
    id: 'talent',
    icon: 'star',
    title: 'Talent Matrix / 9-Box Grid',
    section: 'HR Tools',
    desc: 'A 9-box grid visualisation mapping employee performance vs potential for succession planning.',
    features: [
      '9-box grid layout (Performance × Potential)',
      'Employee tiles positioned on the grid',
      'Colour-coded zones — High Performer, Core Staff, Underperformer',
      'Drag-and-drop positioning',
    ],
    steps: [
      'Go to Talent Matrix from the sidebar',
      'View the 9-box grid with all employees plotted',
      'Each employee is positioned by performance and potential scores',
      'Top-right = high potential high performers (future leaders)',
      'Bottom-left = underperformers (needs intervention)',
    ],
    tips: [
      'Use for succession planning and identifying future leaders',
      'Review quarterly after performance evaluations',
    ],
    related: ['performance', 'employees', 'training'],
  },
  {
    id: 'ask-ai',
    icon: 'message-chatbot',
    title: 'Ask AI',
    section: 'HR Tools',
    desc: 'AI-powered HR assistant that searches local skill files first, then falls back to DeepSeek AI for answers.',
    features: [
      'Chat interface for asking HR-related questions',
      'Local skill.md file search for Malaysia-specific policies',
      'Fallback to DeepSeek AI for broader questions',
      'Skill file management (add/delete)',
    ],
    steps: [
      'Go to Ask AI from the sidebar',
      'Type your HR question in the chat input',
      'The system searches local skill files first',
      'If no local match, it queries DeepSeek AI',
      'View skill files by clicking the "Skills" button',
    ],
    tips: [
      'Skill files cover EA 1955, EPF/SOCSO, OT, leave, and more',
      'Questions about Malaysia-specific laws are answered from skill files',
    ],
    related: ['reports', 'dashboard'],
  },
  {
    id: 'admin',
    icon: 'user-shield',
    title: 'Admin',
    section: 'System',
    desc: 'System administration for user management and AI connector configuration.',
    features: [
      'User list with username, email, role, status',
      'Add/edit/delete users',
      'Hierarchy level and approval level configuration',
      'AI Connectors tab — add/edit/test AI providers',
      'API key show/hide toggle',
      'Connected/Not connected status badges',
    ],
    steps: [
      'Go to Admin from the sidebar',
      'The Users tab shows all system users',
      'Click "Add User" to create a new login account',
      'Set role, hierarchy level, and approval level',
      'Click "AI Connectors" tab to manage AI providers',
      'Add a provider with name, model, and API key',
      'Click "Test Connection" to verify the provider works',
    ],
    tips: [
      'Only Admin role users can access this page',
      'Default AI provider is set in the first connector row',
      'API keys are stored encrypted in the database',
    ],
    related: ['ask-ai', 'matrix'],
  },
  {
    id: 'user-manual',
    icon: 'book-2',
    title: 'User Manual',
    section: 'System',
    desc: 'This page — a comprehensive guide to all modules in MyHRM Pro.',
    features: [
      'Complete documentation for all modules',
      'Searchable by module name or feature',
      'Filter by section (Core, HR Tools, Workforce, etc.)',
      'Step-by-step guides for common tasks',
    ],
    steps: [
      'This page is your reference — search or browse by section',
      'Each module has a description, features, and how-to steps',
      'Use the search bar at the top to find specific features',
    ],
    tips: [
      'Bookmark this page for quick reference',
      'New features are documented here as they are added',
    ],
    related: [],
  },
];

const sections = [...new Set(modules.map(m => m.section))];

export default function UserManualPage() {
  const [search, setSearch] = useState('');
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const [activeModule, setActiveModule] = useState<string | null>(null);

  const filtered = modules.filter(m => {
    const matchSearch = !search || m.title.toLowerCase().includes(search.toLowerCase()) || m.desc.toLowerCase().includes(search.toLowerCase()) || m.features.some(f => f.toLowerCase().includes(search.toLowerCase()));
    const matchSection = !activeSection || m.section === activeSection;
    return matchSearch && matchSection;
  });

  const openModule = activeModule ? modules.find(m => m.id === activeModule) : null;

  return (
    <div className="view" style={{ maxWidth: 960, margin: '0 auto' }}>
      <div className="card" style={{ marginBottom: 20 }}>
        <div className="card-hdr">
          <div>
            <h2 className="card-title"><i className="ti ti-book-2" style={{ color: 'var(--tiffany)' }}></i> User Manual</h2>
            <p style={{ fontSize: 13, color: 'var(--muted)', marginTop: 2 }}>Complete guide to all MyHRM Pro modules</p>
          </div>
        </div>

        <div className="form-row" style={{ gap: 10, marginTop: 8 }}>
          <div className="form-group" style={{ flex: 1, marginBottom: 0 }}>
            <div style={{ position: 'relative' }}>
              <i className="ti ti-search" style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: 'var(--muted)', fontSize: 15 }}></i>
              <input className="form-input" placeholder="Search modules, features, or keywords..." value={search}
                onChange={e => setSearch(e.target.value)} style={{ paddingLeft: 36 }} />
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 12 }}>
          <button className={'btn btn-xs ' + (!activeSection ? 'btn-primary' : 'btn-ghost')} onClick={() => setActiveSection(null)}>All</button>
          {sections.map(s => (
            <button key={s} className={'btn btn-xs ' + (activeSection === s ? 'btn-primary' : 'btn-ghost')} onClick={() => setActiveSection(activeSection === s ? null : s)}>{s}</button>
          ))}
        </div>
      </div>

      {openModule ? (
        <div className="card">
          <button className="btn btn-ghost btn-xs" onClick={() => setActiveModule(null)} style={{ marginBottom: 16 }}>
            <i className="ti ti-arrow-left"></i> Back to all modules
          </button>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
            <div style={{ width: 44, height: 44, borderRadius: 10, background: 'var(--tiffany-lt)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <i className={'ti ti-' + openModule.icon} style={{ fontSize: 20, color: 'var(--tiffany)' }}></i>
            </div>
            <div>
              <h2 style={{ fontSize: 18, fontWeight: 600, color: 'var(--text)' }}>{openModule.title}</h2>
              <span style={{ fontSize: 11, color: 'var(--muted)', fontWeight: 500 }}>{openModule.section}</span>
            </div>
          </div>

          <p style={{ fontSize: 14, color: 'var(--text)', lineHeight: 1.6, marginBottom: 20 }}>{openModule.desc}</p>

          <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
            <i className="ti ti-list-check" style={{ color: 'var(--tiffany)' }}></i> Key Features
          </h3>
          <ul style={{ marginBottom: 20, paddingLeft: 24 }}>
            {openModule.features.map((f, i) => (
              <li key={i} style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.6, marginBottom: 4 }}>{f}</li>
            ))}
          </ul>

          <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
            <i className="ti ti-steps" style={{ color: 'var(--tiffany)' }}></i> How to Use
          </h3>
          <ol style={{ marginBottom: 20, paddingLeft: 24 }}>
            {openModule.steps.map((s, i) => (
              <li key={i} style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.6, marginBottom: 4 }}>{s}</li>
            ))}
          </ol>

          {openModule.tips && openModule.tips.length > 0 && (
            <>
              <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
                <i className="ti ti-bulb" style={{ color: 'var(--amber)' }}></i> Tips & Notes
              </h3>
              <div style={{ background: 'var(--amber-lt)', borderRadius: 8, padding: '12px 16px', marginBottom: 20 }}>
                {openModule.tips.map((t, i) => (
                  <p key={i} style={{ fontSize: 12, color: 'var(--text)', lineHeight: 1.5, marginBottom: i < openModule.tips!.length - 1 ? 6 : 0 }}>
                    <i className="ti ti-info-circle" style={{ color: 'var(--amber)', marginRight: 4 }}></i> {t}
                  </p>
                ))}
              </div>
            </>
          )}

          {openModule.related && openModule.related.length > 0 && (
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 12, color: 'var(--muted)', display: 'flex', alignItems: 'center', gap: 4 }}>
                <i className="ti ti-link"></i> Related:
              </span>
              {openModule.related.map(r => {
                const rel = modules.find(m => m.id === r);
                return rel ? (
                  <button key={r} className="btn btn-xs btn-ghost" onClick={() => setActiveModule(r)}>
                    <i className={'ti ti-' + rel.icon}></i> {rel.title}
                  </button>
                ) : null;
              })}
            </div>
          )}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {sections.map(section => {
            const sectionModules = filtered.filter(m => m.section === section);
            if (sectionModules.length === 0) return null;
            return (
              <div key={section}>
                <h3 style={{ fontSize: 13, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8, paddingLeft: 4 }}>
                  {section}
                </h3>
                <div style={{ display: 'grid', gap: 10, gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))' }}>
                  {sectionModules.map(m => (
                    <div key={m.id} className="card" style={{ cursor: 'pointer', padding: '14px 16px', transition: 'all .15s' }}
                      onClick={() => setActiveModule(m.id)}
                      onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--tiffany)')}
                      onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--border)')}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                        <div style={{ width: 32, height: 32, borderRadius: 8, background: 'var(--tiffany-lt)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                          <i className={'ti ti-' + m.icon} style={{ fontSize: 16, color: 'var(--tiffany)' }}></i>
                        </div>
                        <div style={{ fontWeight: 600, fontSize: 13, color: 'var(--text)' }}>{m.title}</div>
                      </div>
                      <p style={{ fontSize: 12, color: 'var(--muted)', lineHeight: 1.5, marginBottom: 8 }}>{m.desc}</p>
                      <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                        {m.features.slice(0, 3).map((f, i) => (
                          <span key={i} style={{ fontSize: 10, background: 'var(--gray-50)', borderRadius: 4, padding: '2px 6px', color: 'var(--muted)' }}>{f}</span>
                        ))}
                        {m.features.length > 3 && (
                          <span style={{ fontSize: 10, color: 'var(--tiffany)', fontWeight: 500 }}>+{m.features.length - 3} more</span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}

          {filtered.length === 0 && (
            <div className="card" style={{ textAlign: 'center', padding: 40 }}>
              <i className="ti ti-search-off" style={{ fontSize: 32, color: 'var(--muted)', marginBottom: 8 }}></i>
              <p style={{ fontSize: 14, color: 'var(--muted)' }}>No modules match your search</p>
            </div>
          )}
        </div>
      )}

      <div style={{ marginTop: 24, padding: '16px 20px', borderRadius: 10, background: 'var(--gray-50)', fontSize: 12, color: 'var(--muted)', textAlign: 'center' }}>
        MyHRM Pro Malaysia Edition &copy; {new Date().getFullYear()} — {modules.length} modules documented
      </div>
    </div>
  );
}
